#!/bin/sh
# 
## Author: Daniel Berg (daniel@dab.works)
##  2015-06-21
# Uniweb dynDNS update script for asus routers running asuswrt-merlin custom firmware 
# Supported asus models:  RT-AC56U, RT-N66U, RT-AC66U, RT-AC68U, RT-AC68P, RT-AC87U, RT-AC3200
## Sources:
# https://github.com/RMerl/asuswrt-merlin 
# http://support.uniweb.no/hc/no/articles/200121582-Hvordan-sette-opp-dynamisk-DNS-dynDNS-
# https://github.com/RMerl/asuswrt-merlin/wiki/Custom-DDNS
#
# Notice: script not using ssl so pass is sent in plaintext on request!

# User info
USERNAME="yourdomain.org"
PASSWORD="password"
HOSTNAME="host.yourdomain.org"

# get public ip 
MYIP=$(curl -s  dns.uniweb.no/checkip.php | sed 's/^.*: \([^<]*\).*$/\1/')

# math ip to hostname and save reply 
REPLY=$(curl -s --user $USERNAME:$PASSWORD "http://dns.uniweb.no/DynDNSServer/?hostname=$HOSTNAME&myip=$MYIP")

# check for the reply is a "success"  and notify router that ddns was updated (NoCHG = no change, IPCHG = changed ip)
# TODO: replace with case switch
if [ $REPLY = 'NoCHG' ] || [ $REPLY = 'IPCHG' ]; then
  /sbin/ddns_custom_updated 1

# notify of failure
#
# the two returned errors would be "WFPW"(wrong passwd), or "WRGHost Client error"
# TODO: look into whether its possible modify router script to return spesific error.
else 
  /sbin/ddns_custom_updated 0
fi

