#!/usr/bin/env bash
# Copyright (c) 2025 Daniel Berg <mail@roosta.sh>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the “Software”), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
# of the Software, and to permit persons to whom the Software is furnished to do
# so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# BEGIN_DOC
# ### [generate-readme.sh](./generate-readme.sh)
#
# Generates this readme, by extracting docs between comment markers. Support
# additional filetypes by adding to `comment_markers`
#
# Usage:
# ```sh
# ./generate-readme.sh
# ```
# 
# License [MIT](./LICENSE)
# END_DOC

output="README.md"
script_name=$(basename "$0")

# Define file types and their comment markers
declare -A comment_markers
comment_markers[sh]="#"
comment_markers[py]="#"
comment_markers[mjs]="\/\/"

# Header
cat > "$output" << EOF
Scripts
=========

These are utility scripts I use on my systems that isn't a package, or is
simple enough to warrant a script file. These files are in flux, due to
changing requirements and environments.

- Companion repo for for my [dotfiles](https://github.com/roosta/dotfiles)

## Branches


| Branch | Description |
|--------|-------------|
| [**main**](https://github.com/roosta/scripts) | Most current up to date scripts I use on the daily. |
| [**deprecated**](https://github.com/roosta/scripts/tree/deprecated) | Deprecated scripts not in use |


## Script descriptions

Short descriptions for each script, attribution & licensing where applicable.

EOF

# Script docs
# Iterate over comment_markers to extract docs from script filetypes
# Comment syntax varies across different filetypes.
file_count=0
for ext in "${!comment_markers[@]}"; do
  marker="${comment_markers[$ext]}"
  for script in *."$ext"; do
    [ -e "$script" ] || continue
    {
      sed -n "/^${marker} BEGIN_DOC/,/^${marker} END_DOC/p" "$script" \
        | sed -e "s/^${marker} //" -e "s/^${marker}$//" \
        | grep -v "BEGIN_DOC\|END_DOC"
    } >> "$output"
  ((++file_count))
  done
done

# Footer
timestamp=$(date "+%Y-%m-%d %H:%M:%S")
cat >> "$output" << EOF

## Licences

See individual script headers, or attached licenses in [LICENSES](./LICENSES)

- [CC BY-SA 4.0](./LICENSES/CC-BY-SA-4.0-LICENSE.txt) 
- [GFDL-1.3](./LICENSES/GFDL-1.3-LICENSE.txt)
- [GPL-3.0](./LICENSES/GPL-3.0-LICENSE.txt)
- [MIT LICENSE](./LICENSES/MIT-LICENSE.txt)

---

*This README was automatically generated by \`$script_name\` on $timestamp*
EOF

echo "[$script_name] Done! Processed $file_count files."
echo "[$script_name] README.md has been updated with timestamp: $timestamp"
