#+TITLE: Roostas utils

* Information
This repo is basically a dumping ground for various scripts/utils/whatever that
are kinda one-shot stuff that doesn't fit in a project. Probably not very useful
to anyone but me but I'll include some information on each one I can still
remember what does

Some of these scripts I just grabbed off of various sources, wikis, the likes,
and have stuck around long after their expiration date. Hard to delete stuff.

* Scripts
** add_font.sh
   Just add a new font to system by making fontdir and fontscale, and refreshing font cache.
   Really basic stuff but I kept forgetting so here's the script ensuring I'll never remember.
** arch_updates.sh
   Displays the number of package updates pending for an Arch Linux installation.

   This is grabbed straight from [[https://github.com/ultrabug/py3status][py3status]], I think I made some modifications on
   the print output but other than that it's the same.
** bandwidth
   Output bandwidth usage to stdout.
   Did not write this, grabbed it from somewhere I can't remember

   Authors:
   - Copyright (C) 2012 Stefan Breunig <stefan+measure-net-speed@mathphys.fsk.uni-heidelberg.de>
   - Copyright (C) 2014 kaueraal
   - Copyright (C) 2015 Thiago Perrotta <perrotta dot thiago at poli dot ufrj dot br>
** bandwidth_alt.sh
   Alternative script for outputting bandwidth to stdout. Think this one is
   broken currently, don't remember what I used it for :)
** battery
   Output battery status to stdout
** byzanz_gui.sh
   GUI script for byzanz, a script used for recording GIF screencasts. Have
   since moved to other solutions but its here for posterity.

   Author: (c) Rob W 2012, modified by MHC (http://askubuntu.com/users/81372/mhc)
** chdisp_nvidia.sh
   Script for changing output displays using nvidia cards. It also changes audio sink.

   Write this because I have a couch and a desk, and need to switch between them by using a shortcut.
   I couldn't find a script that changes both displays and audio sink so here we are.

   It uses pre-defined layouts and takes a single argument. =desk=, =tv=, =mix=
** chdisp_xrandr.sh
   Same as above but using xrandr instead of nvidia-settings for setting layout
** cpu_temp
   Output CPU temperature to stdout. Uses lm_sensors internally, just formats output a bit.
   Used with i3blocks

   Authors:
   - Copyright 2014 Pierre Mavro <deimos@deimos.fr>
   - Copyright 2014 Vivien Didelot <vivien@didelot.org>
   - Copyright 2014 Andreas Guldstrand <andreas.guldstrand@gmail.com>
   - Copyright 2014 Benjamin Chretien <chretien at lirmm dot fr>
** cpu_usage
   Output CPU usage to stdout with pre-pended color values for use in i3blocks
** crypthelper.sh
   Script to simplify opening and mounting dm-crypt encrypted partitions.
   Really not terribly useful I just kept forgetting how to do it, so I wrote this.

   It is used like so:
   #+BEGIN_SRC shell
   ./crypthelper.sh open /dev/sdh1 my-encrypted-device-name # gets mounted in ~/mnt/[name]
   ./crypthelper.sh close my-encrypted-device-name
   #+END_SRC
** ddns_start.sh
   Wrote this for [[https://asuswrt.lostrealm.ca/][asuswrt-merlin]], to setup uniweb.no DDNS on my router a long time ago.
   This probably doesn't work anymore, and just keeping it here in case I need to
   do something similar at some point
** devwatch.sh
   This is some sort of watch script for removable devices and mounting it using ~udiskctl~
   Probably found it on the [[https://wiki.archlinux.org/][Arch Linux wiki]]
** dialog_demo.sh
   Demo various dialog boxes using ~whiptail~, ~ncurses~, ~GTK dialog~, ~KDE Dialog~
   I did not write this, only use it for reference. I stupidly never noted where I got it from.
** disk
   Disk usage script used with [[https://github.com/vivien/i3blocks][i3blocks]], it defaults to ~home~, but takes settings from [[https://github.com/vivien/i3blocks][i3blocks]] config
   Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>
** dropboxd_status.py
   Display status of Dropbox daemon.
   I meant to use this outside of py3status hence its presence here, but haven't
   gotten around to modifying it yet.
   Requires: dropbox-cli
   Used with: [[https://github.com/ultrabug/py3status][py3status]]

   - Author: Tjaart van der Walt (github:tjaartvdwalt)
   - License: BSD
**
** dropdown_terminal.sh
   Script I grabbed from [[https://github.com/kalq/dotfiles/blob/macbook/scripts/bin/dropdown_terminal.sh][here]] and does some sorcery to create a dropdown terminal in bspwm.
   [[https://www.reddit.com/r/unixporn/comments/60qw8z/bspwm_bite_my_shiny_metal_ass/][This]] is the unixporn entry that linked me to the script
   It's my intention to modify this to work on [[https://github.com/kalq/dotfiles/blob/macbook/scripts/bin/dropdown_terminal.sh][i3wm]]
** emacs_file_opener.sh
   This uses emacsclient to open file ~$1~ at line ~$2~
   What I usually do is to add this to a project.clj using [[https://github.com/bhauman/lein-figwheel][figwheel]]:

   #+BEGIN_SRC clojure
   :figwheel {:open-file-command    "script/emacs_file_opener.sh"}
   #+END_SRC

   and I can click on the error dialog in the browser to have Emacs goto error.
